##### Input data

inputDataFile: ./data/u-fronting.csv
features: 
- DCT0
- DCT1
- DCT2
group: age
label: phoneme
initial: phoneme
word: word
speaker: spk
subsetSpeakers: NULL
subsetLabels: NULL

##### Setup

createPopulationMethod: speaker_is_agent
bootstrapPopulationSize: 50
initialMemoryResampling: FALSE
initialMemoryResamplingFactor: 2.0
removeOriginalExemplarsAfterResampling: FALSE

##### Production

productionBasis: word
productionResampling: SMOTE
productionResamplingFallback: label
productionMinTokens: 10
productionSMOTENN: 5

##### Perception

perceptionModels: singleGaussian
memoryIntakeStrategy: 
- mahalanobisDistance
- maxPosteriorProb
mahalanobisProbThreshold: .95
posteriorProbThr: 1/3
perceptionOOVNN: 5

##### GMM-based phonology

computeGMMsInterval: 100
purityRepetitions: 5
purityThreshold: 0.75

##### Forgetting

forgettingRate: 1

##### Interactions

interactionPartners: betweenGroups
speakerProb: NULL
listenerProb: NULL

##### Runs

runMode: single
multipleABMRuns: 5
nrOfSnapshots: 1
interactionsPerSnapshot: 0

##### Other options

rootLogDir: ./logDir
notes: u-fronting demo
